TACODEV-774: enable metric on argo series
openinfradev/tacoplay pull request #108
Opened 2021-07-01 08:55 UTC by intelliguy

**Objective**
Argo worflow/CD도 prometheus metric으로 수집할 수 있다. Argo worklfow/CD의 metric을 조사하고, Argo CD 의 주요 metric 수집한다.
argo cd/workflow exporter 존재함, 서비스 모니터 생성해서 prometheus로 데이터 저장 확인 (lma-addons) 
grafana dashboard 까지 추가, 확인 (grafana labs에 있는 대시보드 활용) 

**Doing with this PR**
argo 설치시 metric을 생성할 수 있도록 설정

2021-07-02 05:19 UTC, zugwan requested changes

2021-07-02 05:19 UTC, zugwan commented on roles/decapod/tasks/argo.yml
> +    src: "{{ role_path }}/templates/argowf_values.j2"
파일 명이 커밋에 포함된 것과 다릅니다: argowf__values.j2

2021-07-02 06:06 UTC, intelliguy commented on roles/decapod/tasks/argo.yml
> +    src: "{{ role_path }}/templates/argowf_values.j2"
아래 파일 만들면서 오타가(_가 한번더...)
수정해서 다시 올릴께요

2021-07-02 06:24 UTC, robertchoi80 commented
argo-workflow v3 로 가면서 사용하는 차트가 바뀌어서 value override하는 부분에서 문제가 있을것 같습니다ㅠ
https://github.com/openinfradev/tacoplay/pull/109

2021-07-06 04:17 UTC, estherk0 commented on roles/decapod/templates/argowf_values.j2
> +  enabled: true
이 부분 잘 못 들어간 것 같습니다. 밑에 있는 metricsConfig: 랑 겹치는데 삭제해도 되지 않을까요?

2021-07-06 04:18 UTC, intelliguy commented on roles/decapod/templates/argowf_values.j2
> +  enabled: true
네 맞네요...수정해서 올리겠습니다.

2021-07-07 07:00 UTC, zugwan approved these changes

2021-07-08 06:08 UTC, merged