Decapod v2에서 오프라인 환경 구성을 지원
openinfradev/tacoplay pull request #128
Opened 2021-11-11 01:51 UTC by zugwan

- site-prepare 플레이북 실행 시 수행되는 태스크 수정
- 기존 argo/argocd 설치 부분 제거

2021-11-15 01:41 UTC, robertchoi80 commented on roles/prepare-artifact/tasks/download_artifacts.yml
> -- name: Render manifest yaml for real deployment
이 부분은 무슨 목적으로 존재했던 코드일까요?  바로 위의 task와 거의 중복인 듯 한데..

2021-11-15 01:45 UTC, zugwan commented on roles/prepare-artifact/tasks/download_artifacts.yml
> -- name: Render manifest yaml for real deployment
바로 이전 태스크가 hanu-reference 사이트를 렌더링해서 나온 manifests를 가지고 Helm 차트와 컨테이너 이미지를 다운로드 하는 것이고 삭제된 내용은 실제 배포 때 사용할 hanu-reference-offline manifests를 렌더링해서 tacoplay.tar.gz에 들어가도록 하는 부분입니다. (1.0 버전에서는 사이트 이름이 조금 다르긴 합니다)

이전 버전에서는 구축할 manifests를 site-prepare 단계에서 렌더링 후 가져가는 방식이었다면 2.0 부터는 내부의 git 저장소로부터 필요에 따라 렌더링하기 때문에 삭제하였습니다.

2021-11-15 01:56 UTC, robertchoi80 approved these changes

2021-11-15 05:36 UTC, ktkfree approved these changes

2021-11-15 07:16 UTC, Jaesang commented
https://jenkins.hanu-ci.io/job/site-prepare-pangyo-vm/119/console

`docker_image` 사용 시 `source`가 누락된 부분이 있어 업데이트 필요합니다.

2021-11-15 14:45 UTC, Jaesang requested changes

2021-11-15 14:45 UTC, Jaesang commented on roles/decapod/tasks/main.yml
> +- name: create namespace for decapod-bootstrap
해당 작업이 실행되지 않습니다.
https://jenkins.hanu-ci.io/job/site-prepare-pangyo-vm/121/consoleFull

2021-11-16 01:32 UTC, zugwan commented on roles/decapod/tasks/main.yml
> +- name: create namespace for decapod-bootstrap
네임스페이스 생성 태스크가 실행 안된다는 말씀이시죠? https://github.com/openinfradev/tacoplay/blob/843f5b45fdf5f82e6b55e70f807886618d3c124f/extra-playbooks/site-prepare.yml#L26 에서 site-prepare에서는 'download' 태그와 함께 호출하기 때문에 설치 과정에 필요한 작업은 실행되지 않습니다.

2021-11-16 01:35 UTC, Jaesang approved these changes

2021-11-16 01:36 UTC, merged