Site prepare rook decapod
openinfradev/tacoplay pull request #83
Opened 2021-05-24 01:12 UTC by zugwan

offline 환경 구축용 수정입니다. online/offline용 태스크를 분리하지 않고 필요한 부분들은 모두 다운로드 후 사용하는 형태로 하였습니다.

2021-05-24 06:24 UTC, robertchoi80 commented on roles/ceph/rook/tasks/main.yml
> +  set_fact:
동일한 변수명으로 그대로 set_fact하는 건 어떤 목적인가요?

2021-05-25 01:29 UTC, zugwan commented on roles/ceph/rook/tasks/main.yml
> +  set_fact:
role에서 정의된 변수는 동일한 play내 에서 유효합니다. 기존 site-prepare 플레이북 구조를 변경하지 않고 rook, decapod 관련 내용만 추가하면서 아래와 같이 정리를 했었습니다. 아래 1,2 부분이 별도의 play로 실행되기 때문에 set_fact로 호스트 변수화하지 않으면 prepare-artifact에서 rook, decapod role 변수 접근이 불가능합니다.
1) online/offline 구분 없이 설치 과정에서 필요한 태스크는 각 role 내에서 수행, site-prepare에서 태그 지정 호출: https://github.com/openinfradev/tacoplay/blob/4a69fa4caa1ff7e86be64005576cbe79de83347e/extra-playbooks/site-prepare.yml#L16
2) offline만 한정된 컨테이너 이미지 다운로드 작업은 prepare-artifact에서 수행: https://github.com/openinfradev/tacoplay/blob/4a69fa4caa1ff7e86be64005576cbe79de83347e/extra-playbooks/site-prepare.yml#L51
참고: https://stackoverflow.com/questions/65322926/access-variable-from-one-role-in-another-role-in-an-ansible-playbook-with-multip

2021-05-25 04:41 UTC, robertchoi80 commented on roles/ceph/rook/tasks/main.yml
> +  set_fact:
네 알겠습니다

2021-05-25 04:41 UTC, robertchoi80 approved these changes

2021-06-01 05:41 UTC, Jaesang requested changes

2021-06-01 05:41 UTC, Jaesang commented on Jenkinsfile
> +            tacoplay_params = "-e kube_version=${params.K8S_VERSION}"
아래 job을 실행하였는데, validate-k8s에서 sonobuoy이미지를 인터넷에서 다운로드 받고있어서 로그를 보니 offline 테스트 시 `online`이 제대로 적용되지 않고있습니다. 특정 부분에서 false가 다시 true가 되는 느낌인데, 로그 한번 검토해주세요 

관련 job: https://jenkins.hanu-ci.io/job/deploy-taco/340/consoleFull

2021-06-01 05:48 UTC, zugwan commented on Jenkinsfile
> +            tacoplay_params = "-e kube_version=${params.K8S_VERSION}"
> 아래 job을 실행하였는데, validate-k8s에서 sonobuoy이미지를 인터넷에서 다운로드 받고있어서 로그를 보니 offline 테스트 시 `online`이 제대로 적용되지 않고있습니다. 특정 부분에서 false가 다시 true가 되는 느낌인데, 로그 한번 검토해주세요
> 
> 관련 job: https://jenkins.hanu-ci.io/job/deploy-taco/340/consoleFull

deploy-taco Jenkins 파일도 수정이 되어서 테스트를 위해  현재 PR 소스 브랜치인 site-prepare_rook_decapod을 바라보는 별도 Job을 추가했습니다: https://jenkins.hanu-ci.io/job/offline-deploy-taco/
6번이 최근 성공한 것입니다.

2021-06-01 06:23 UTC, Jaesang commented on Jenkinsfile
> +            tacoplay_params = "-e kube_version=${params.K8S_VERSION}"
본래 job에서는 수정된 Jenkinsfile을 읽지 못하는군요, 새 job에서 보도록하겠습니다!

2021-06-02 04:16 UTC, Jaesang approved these changes
Test 성공 job link입니다.
https://jenkins.hanu-ci.io/job/offline-deploy-taco/10/console

2021-06-03 05:31 UTC, merged