Decapod V1 관련 태스크 분리 및 온라인 환경 오류 수정
openinfradev/tacoplay pull request #87
Opened 2021-06-04 07:53 UTC by zugwan

- Decapod V1/V2가 호환이 되지 않기 때문에 이를 지정해서 테스트할 수 있도록 Jenkins Job 변수를 추가하였습니다.
- V1 관련 태스크들을 별도로 분리하여 "release-1.0" 경우에만 실행되도록 하였습니다 (참고: v1 관련 내용들이 main 브랜치에서 제거됨 https://github.com/openinfradev/decapod-flow/commit/f4e6300ab198b2631b9e6cf247b218dc034c1d8e)
- V1 관련 추가된 오프라인 태스크 중 온라인 환경에서 오류가 발생할 수 있는 부분을 수정하였습니다: helm-repository, container-registry 그룹 및 호스트 정의가 안되어 있을 경우

2021-06-04 08:04 UTC, Jaesang requested changes

2021-06-04 08:04 UTC, Jaesang commented on Jenkinsfile
> +      defaultValue: 'main'
요기 ,가 빠졌습니다 😭

2021-06-04 10:03 UTC, zugwan commented on Jenkinsfile
> +      defaultValue: 'main'
수정하였습니다~

2021-06-07 01:58 UTC, jabbukka approved these changes

2021-06-07 01:59 UTC, merged